In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [8]:
data=pd.read_csv('/content/nba (1).csv')
data.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [9]:
data.shape

(457, 9)

In [10]:
data.isna().sum()

Name         0
Team         0
Number       0
Position     0
Age          0
Height       0
Weight       0
College     84
Salary      11
dtype: int64

In [12]:
data1 = data.drop('Name',axis=1)

In [13]:
data1=pd.get_dummies(data1)

In [14]:
data1.head()

,Number,Age,Weight,Salary,Team_Atlanta Hawks,Team_Boston Celtics,Team_Brooklyn Nets,Team_Charlotte Hornets,Team_Chicago Bulls,Team_Cleveland Cavaliers,...,College_Washington State,College_Weber State,College_Westchester CC,College_Western Carolina,College_Western Kentucky,College_Western Michigan,College_Wichita State,College_Wisconsin,College_Wyoming,College_Xavier
0,0.0,25.0,180.0,7730337.0,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,99.0,25.0,235.0,6796117.0,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,30.0,27.0,205.0,NaN,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,28.0,22.0,185.0,1148640.0,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,8.0,29.0,231.0,5000000.0,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [18]:
X=data1.drop('Salary',axis=1)
Y=data1['Salary']

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=42)

In [21]:
from sklearn.linear_model import LogisticRegression

In [24]:
LRmodel=LogisticRegression()
LRmodel=LRmodel.fit(X_train,Y_train)

ValueError: Input y contains NaN.